name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      
      - uses: actions/setup-node@v4
        name: Install nodejs
        with:
          node-version: '21.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: pnpm install
        name: Install dependencies

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
